### ISSUE TITLE
Incorporate all of this into a wearable device

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/exploring-space-with-minecraft#3]
@MarcScott it looks like you have got some cut and paste problems on each worksheet with:

+Now move on to [worksheet 2](worksheet2.md) to learn how to incorporate all of this into a wearable device.
+Now move on to [worksheet 3](worksheet3.md) to learn how to incorporate all of this into a wearable device.
+Now move on to [worksheet 4](worksheet4.md) to learn how to incorporate all of this into a wearable device.

We arent making a wearable device!

**Comment by MarcScott** [comment]
Fixed
